### ISSUE TITLE
add functionality to shut down gracefully in worker manager

### ISSUE THREAD

**Issue by shubham7saxena** [gojekfarm/probed#1]
https://github.com/gojekfarm/ping-kong/blob/186d13757d13ab4e4bca18fd10035efe9569f400/worker.go#L15

**Comment by rShetty** [comment]
This commit https://github.com/gojekfarm/ping-kong/commit/36ccf52128695a6d4e3fd53e2f85ac3a70f8fb96 should fix this issue

**Comment by rShetty** [comment]
Closing this, has already been integrated.
